#spring.application.name=account
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3014
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: account-service

# Mü?teri servisinin adresi buraya yaz?l?r:
customer-service:
  url: http://localhost:8081/api/customers