#spring.application.name=core-service
#
#server.port=8081

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3014
  jpa:
    hibernate:
      ddl-auto: update\
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect