#spring.application.name=core-service
#
#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.jpa.properties.hibernate.default_schema=banking_schema
#
#spring.datasource.username=postgres
#spring.datasource.password=3014
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.port=8081

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3014
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: core-service